---
- name: Instalar servidor web
  apt:
    name: "{{ web_package }}"
    state: present
    update_cache: yes

- name: Asegurar que el servicio est√© iniciado
  service:
    name: "{{ web_service }}"
    state: started
    enabled: yes

- name: Copiar archivo HTML
  template:
    src: index.html.j2
    dest: "{{ web_root }}/index.html"
    mode: "0644"
